### ISSUE TITLE
unitary_test does not pass possible due to bug in mesti_main.jl

### ISSUE THREAD

**Issue by YumingN** [complexphoton/MESTI.jl#4]
Hi there,

I'm trying to use your code, and I cannot pass the tests after installation.

The runtests.jl does not pass as it fails at condition checking at line 1347 and line 1566 in mesti_main.jl, where the code seems to check whether B_ii and C_ii are empty. However, it checks by isassigned(B_ii), passing only one input, and then it throws an error. I played with this Julia function that it sometimes works with one input, but I do not find such usage online and I don't understand the Julia source code of this. 

Commenting out the two condition-checkings will pass the tests, so I think it could be a bug of either the usage or Julia.

Best

**Comment by hochunlin** [comment]
Hi there,

The bug came from the version between Julia 1.10 and Julia 1.9 giving us different results in line 1347 and line 1566.

For example, in Julia 1.9
```
julia> B_ii = Vector(undef, 3);
julia> B_ii[1] = 1;
julia> isassigned(B_ii)
true

```
but in Julia 1.10
```
julia> B_ii = Vector(undef, 3);
julia> B_ii[1] = 1;
julia> isassigned(B_ii)
false

```
So when you used Julia 1.10, it would cause the bug. We fixed it in the latest version (v.0.4.2) and it works for both Julia 1.9 & Julia 1.10. Thanks.
